examples/css辞書/flexbox/flexbox/project/ajax/urls.py
from django.urls import path
from . import views

app_name='ajax'
urlpatterns = [
	path("ajax/", views.ajax, name="ajax"),
	path("ajax2/", views.ajax2, name="ajax2"),
]

examples/css辞書/flexbox/flexbox/project/app/urls.py
from . import views
from django.views.generic import TemplateView
from ajax.views import z
from django.urls import path, re_path, include



app_name = "app"
urlpatterns = [
    path("index/",views.index, name="index"),
]

examples/css辞書/flexbox/flexbox/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#同じapp.urlsを指定している場合、警告が出る場合があるが、
#namespaceを別々に設定することで回避できる。
urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/",include("app.urls",namespace="short"),),
    #ajaxは本編に関係ない
    path("ajax/", include("ajax.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

examples/css辞書/flexbox/flexbox/project/ajax/models.py
from django.db import models

# Create your models here.

examples/css辞書/flexbox/flexbox/project/app/models.py
from django.db import models
from pathlib import Path

examples/css辞書/flexbox/flexbox/project/app/forms.py
from django import forms
from .models import *
from django.urls import reverse
from django.urls import reverse_lazy


class CssForm(forms.Form):
    value=forms.ChoiceField(label="background-clipの値", choices=[(0, "border-box"),(1, "padding-box"),(2, "content-box"), ])

examples/css辞書/flexbox/flexbox/project/ajax/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import os
import subprocess
from pathlib import Path
import psutil
import re


def ajax(request):
    cmd="taskkill /f /T /im chromedriver.exe"
    subprocess.Popen(cmd,shell=True)
    return HttpResponse("")


def ajax2(request):
    filepath=request.GET.get("filepath")
    text=""
    with open(filepath, "r",encoding="utf-8_sig") as f:
           for i in f.readlines():
                text+=i
    d={"text": text, "title":filepath}

    return JsonResponse(d)



def z():
    base_path = Path.cwd()
    file_path_list=[]
    hierarchy_list=[]
    for i in base_path.glob("**/*"):
       if not ("ajax" in str(i)) and not ("migrations" in str(i)) and not ("rightside.html" in str(i)) and not ("footer.html" in str(i)) and not ("footer_origin.html" in str(i)) and not ("views2.py" in str(i)) and not (".vscode" in str(i)) and not ("db.sqlite" in str(i)) and not ("manage.py" in str(i)) and not ("__pycache__" in str(i)): 
           mojiretu=str(i).replace(str(base_path)+"\\","")
           find_list=re.findall("\\\\", mojiretu) #ここ重要
           for ii in range(len(find_list)):
               mojiretu=mojiretu.replace("\\", "/")
           file_path_list.append(mojiretu)
           hierarchy_list.append(len(find_list))
    max_hierarchy_number=max(hierarchy_list)
    d={"file_path_list": file_path_list, "max_hierarchy_number":max_hierarchy_number}
    return d

examples/css辞書/flexbox/flexbox/project/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotAllowed
import os
from pathlib import Path
import re
from ajax.views import z
from django.views import View
from django.urls import reverse
from django.views import generic
from .forms import CssForm

d = z()
d["mode"] = "index"

def index(request):
    if request.method=="POST":
          f=CssForm(request.POST)
          if f.is_valid():
                 d["form"]=f
                 choice_list=f.fields['value'].choices
                 print(choice_list)
                 d["choice"]=choice_list[int(f.cleaned_data["value"])][1]
                 print (d["choice"])
                 with open("app/static/app/base_origin.css", "r") as ff:
                       data = ff.read()
                       data1=data.replace("--**__**", d["choice"])
                 with open("app/static/app/base.css", "w") as ff:
                       ff.write(data1)
                 return render(request, "app/index.html", d)
    else:
          f=CssForm()
          d["form"]=f
    return render(request, "app/index.html", d)      


    

examples/css辞書/flexbox/flexbox/project/app/templates/app/footer.html
<form id=tekitou>
  <input type="hidden" name="pid" value="17616">
</form>
<script>
  /*
windowを閉じたらクロームドライバーをキルする。
  */

/*
  $(window).on("beforeunload", function () {


    $.ajax({

      'url': '{% url "ajax:ajax" %}',
      'type': 'GET',
      'data': $("form#tekitou").serialize(),
      'dataType': 'text',
    })
      .done(function (data) { alert("chromedriverをキルしました" ) });

    return false;


  });
*/
</script>

examples/css辞書/flexbox/flexbox/project/app/templates/app/footer_origin.html
<form id=tekitou>
  <input type="hidden" name="pid" value="----***----***----">
</form>
<script>
  /*
windowを閉じたらクロームドライバーをキルする。
  */

/*
  $(window).on("beforeunload", function () {


    $.ajax({

      'url': '{% url "ajax:ajax" %}',
      'type': 'GET',
      'data': $("form#tekitou").serialize(),
      'dataType': 'text',
    })
      .done(function (data) { alert("chromedriverをキルしました" ) });

    return false;


  });
*/
</script>

examples/css辞書/flexbox/flexbox/project/app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Examples</title>

    <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'app/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous">

    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
  </head>

  <body>
    {{ mode }}
    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          {% if mode == "index" %}
          {% include "app/main.html" %}
          {% endif %}

          {% include "app/footer.html" %}
        </div>
        <div class="col-lg-6">
          {% include "app/rightside.html" %}

        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
  </body>

</html>

examples/css辞書/flexbox/flexbox/project/app/templates/app/main.html
<!-- Page Content -->


<h1 class="mt-5">background-clip</h1>
<p>[参考ページ]<a href="http://www.htmq.com/css3/background-clip.shtml">HTMLクイックリファレンス</a></p>

<div id="b_main">
    <form action="{% url 'app:index' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">送信</button>
    </form>
</div>


{% if request.method == "POST" %}
<div id="a_main" >{{ choice }}</div>

{% endif %}
<hr>

examples/css辞書/flexbox/flexbox/project/app/templates/app/rightside.html
{% load static %}
<h2><b>ファイル構成</b></h2>
<div id="folders"></div>
<hr>
<h2 id="title"></h2>
<pre><div id="ttxt"></div></pre>

<form method="GET" action="{% url 'ajax:ajax2' %}" id="filepath">
  <input type="hidden" name="filepath">
</form>

<script>



var file_path_list={{ file_path_list|safe }};
var max_hierarchy_number={{ max_hierarchy_number }};
var file_path_list_list=[];
for (var i=0; i<file_path_list.length; i++ ){
    var file_path=file_path_list[i].split("/");
    file_path_list_list.push(file_path);
};

var file_path_hierarchy_list=[];
for (var ii=0; ii<max_hierarchy_number+1; ii++){
a=[];    
for (var i of file_path_list_list){

        if (i.length-1==ii){
            a.push(i)
        };
    };
    file_path_hierarchy_list.push(a);
};
file_path_hierarchy_list2=[];
for (var i=0; i<file_path_hierarchy_list.length-1; i++){
    bb=[];
    jj=[];
    cc=[];
    for (var ii of file_path_hierarchy_list[i]){
        var aa=[];
        for (var iii of file_path_hierarchy_list[i+1]){
            dd=iii.slice();
            ee=ii.slice();
            dd.pop();
            ff=ee.join("/")
            gg=dd.join("/")
            if (gg==ff){
                 aa.push(iii[iii.length-1]);
                 hh=gg;
            };

};

if (aa.length!=0){
    aa.unshift(hh);
    cc.push(aa);
};
    };

 file_path_hierarchy_list2.push(cc)   ;
};
var html1="";

 for (var ii of file_path_hierarchy_list2[0]){
    for (var iii in ii){
         if (iii==0){
            html1=html1+"<div class='first_layer'><div class='layer'>"+ii[iii]+"</div>";  
         } else {
            html1=html1+"<div class='"+ii[0]+"/"+ii[iii]+"' style='text-indent:1em'><div class='layer' >"+ii[iii]+"</div></div>";
        };

    };
html1=html1+"</div>"
 };


$("div#folders").html(html1);

for (var i=1; i<file_path_hierarchy_list2.length; i++){
 for (var ii of file_path_hierarchy_list2[i]){
    for (var iii=1; iii<ii.length; iii++){
         var abe = document.createElement("div");
         var bbe=document.createElement("div");
         bbe.setAttribute("class", "layer");
         bbe.setAttribute("style", 'text-indent:'+(i+1)+'em');
         abe.setAttribute("class", ii[0]+"/"+ii[iii]);
         bbe.innerHTML     = ii[iii];
         abe.appendChild(bbe);
         var obj=document.getElementsByClassName(ii[0]);
         for (var iiii=0; iiii<obj.length; iiii++){
         obj[iiii].appendChild(abe);
         }; 

    };

 };
};




$('.layer').click(function() {
        $(this).nextAll().slideToggle(400);
    });

   


     $(document).on("click", ".layer", function(){
         var mojiretu2=$(this).parent("div").attr("class");
         if (mojiretu2.indexOf(".")!=-1){
            $("input[name='filepath']").val(mojiretu2);
            $("form#filepath").submit();
         };

     });


     $(document).on("submit", "form#filepath", function(){
         
             $.ajax({

      'url': '{% url "ajax:ajax2" %}',
      'type': 'GET',
      'data': $("form#filepath").serialize(),
      'dataType': 'json',
    })
      .done(function (data) { 
          $("#ttxt").text(data.text);
          $("h2#title").text(data.title);
      });
    return false;

     });

$(".layer").each(function(index, element) {
         var mojiretu2=$(element).parent().attr("class");
         if (mojiretu2.indexOf(".")==-1){
            $(element).prepend('<img src="{% static 'app/folder_icon.gif' %}" width=20 height=20>');
         } else {
            $(element).prepend('<img src="{% static 'app/document_icon.gif' %}" width=20 height=20>');  
         };

});




</script>