examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/urls.py
from . import views
from django.views.generic import TemplateView
from ajax.views import z
from django.urls import path, re_path, include




app_name = "app"

urlpatterns = [
    path('index/', views.ImgIndexView.as_view(), name='index'),
    path('create/', views.ImgCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ImgUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ImgDeleteView.as_view(), name='delete'),
]

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/models.py
from django.db import models
from pathlib import Path
import os

class Img(models.Model):
    title = models.CharField("タイトル", max_length=255, blank=True)
    file = models.ImageField("ファイル", upload_to='images/', )
    created_at = models.DateTimeField("作成日", auto_now_add=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)
 
    def __str__(self):
        return self.title
 
    def get_filename(self):
        return os.path.basename(self.file.name)






                   
    

       

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/forms.py
from django import forms
from .models import *
from django.urls import reverse
from django.urls import reverse_lazy
from .models import Img
 
 
class ImgForm(forms.ModelForm):
 
    class Meta:
        model = Img
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'file': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotAllowed
import os
from pathlib import Path
import re
from ajax.views import z
from django.views import View
from django.urls import reverse,reverse_lazy
from django.views import generic
from .models import Img
from .forms import ImgForm




 
 
class ImgIndexView(generic.ListView):
    model = Img
    paginate_by = 2
    def get_context_data(self, *args, **kwargs):
        d=super().get_context_data(*args, **kwargs)
        e=z()
        e["mode"]="list"
        d.update(e)
        return d
 
 
class ImgCreateView(generic.CreateView):
    model = Img
    form_class = ImgForm
    success_url = reverse_lazy("app:index")
    def get_context_data(self, *args, **kwargs):
        d=super().get_context_data(*args, **kwargs)
        e=z()
        e["mode"]="form"
        d.update(e)
        return d
 
 
class ImgUpdateView(generic.UpdateView):
    model = Img
    form_class = ImgForm
    success_url = reverse_lazy("app:index")
    def get_context_data(self, *args, **kwargs):
        d=super().get_context_data(*args, **kwargs)
        e=z()
        e["mode"]="form"
        d.update(e)
        return d
 
 
class ImgDeleteView(generic.DeleteView):
    model = Img
    success_url = reverse_lazy("app:index")
    def get_context_data(self, *args, **kwargs):
        d=super().get_context_data(*args, **kwargs)
        e=z()
        e["mode"]="delete"
        d.update(e)
        return d

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/delete_main.html
  <div class="container">
    <form action="" method="POST" enctype='multipart/form-data'>
	  <div class="text-xs-center">
	    <img src="{{ img.file.url }}" alt="{{ img.title }}" width="80" height="80">
	    <p>{{ img.title }}</p>
	    <button type="submit" class="btn btn-outline-primary">削除する</button>
	    <a href="{% url 'app:index' %}" class="btn btn-outline-primary">やめる</a>
	  </div>
	  {% csrf_token %}
		</form>
	</div>	

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/footer.html
<form id=tekitou>
  <input type="hidden" name="pid" value="13244">
</form>
<script>
  /*
windowを閉じたら子プロセスのrunserverをキルする。
  */
  $(window).on("beforeunload", function () {
    $.ajax({

      'url': '{% url "ajax:ajax" %}',
      'type': 'GET',
      'data': $("form#tekitou").serialize(),
      'dataType': 'text',
    })
      .done(function (data) { alert("runserver8080をキルしました。pid:" + data) });
    return false;


  });

</script>

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/form_main.html
<!-- Page Content -->


<h1 class="mt-5">画像アプロダ（CRUD処理を、汎用ビューで）</h1>
<p>[参考ページ]<a href="https://torina.top/detail/293/">Narito blog</a></p>



  <div class="container">
    <form action="" method="POST" enctype='multipart/form-data'>
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">
            {{ field.label }}
          </label>
          <div class="col-sm-10">
            {{ field }}
          </div>
        </div>
      {% endfor %}
      {% csrf_token %}
      <div class="text-xs-center">
        <button type="submit" class="btn btn-outline-primary">送信する</button>
        <a href="{% url 'app:index' %}" class="btn btn-outline-primary">やめる</a>
      </div>
    </form>
  </div>



<a href="{% url 'admin:index' %}">管理画面へ</a>


<hr>

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/img_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Examples</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous">
    <style>
    </style>
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
  </head>

  <body>
    {{ mode }}
    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
            <nav class="navbar navbar-fixed-top navbar-dark bg-info">
                <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
                  &#9776;
                </button>
                <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
                <div class="container">
                  <ul class="nav navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'app:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'app:create' %}">Create</a>
                    </li>
                  </ul>
                  </div>
                </div>
              </nav>
          {% if mode == "delete" %}
          {% include "app/delete_main.html" %}
          {% endif %}

          {% include "app/footer.html" %}
        </div>
        <div class="col-lg-6">
          {% include "app/rightside.html" %}

        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
  </body>

</html>

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/img_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Examples</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous">
    <style>
    </style>
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
  </head>

  <body>
    {{ mode }}
    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
            <nav class="navbar navbar-fixed-top navbar-dark bg-info">
                <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
                  &#9776;
                </button>
                <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
                <div class="container">
                  <ul class="nav navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'app:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" active href="{% url 'app:create' %}">Create</a>
                    </li>
                  </ul>
                  </div>
                </div>
              </nav>
          {% if mode == "form" %}
          {% include "app/form_main.html" %}
          {% endif %}

          {% include "app/footer.html" %}
        </div>
        <div class="col-lg-6">
          {% include "app/rightside.html" %}

        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
  </body>

</html>

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/img_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Examples</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous">
    <style>
    </style>
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
  </head>

  <body>
    {{ mode }}
    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
            <nav class="navbar navbar-fixed-top navbar-dark bg-info">
                <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
                  &#9776;
                </button>
                <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
                <div class="container">
                  <ul class="nav navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link" active href="{% url 'app:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'app:create' %}">Create</a>
                    </li>
                  </ul>
                  </div>
                </div>
              </nav>
          {% if mode == "list" %}
          {% include "app/list_main.html" %}
          {% endif %}

          {% include "app/footer.html" %}
        </div>
        <div class="col-lg-6">
          {% include "app/rightside.html" %}

        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
  </body>

</html>

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/list_main.html
<!-- Page Content -->


<h1 class="mt-5">画像アプロダ（CRUD処理を、汎用ビューで）</h1>
<p>[参考ページ]<a href="https://torina.top/detail/293/">Narito blog</a></p>

<section class="jumbotron text-xs-center">
        <div class="container">
          <h1 class="jumbotron-heading">アップローダーサンプル</h1>
          <p class="lead text-muted">アップローダーのサンプルです。Bootstrap4を使っています。</p>
          <p>
            <a href="#" class="btn btn-primary">飾りボタン</a>
            <a href="#" class="btn btn-secondary">飾りボタン</a>
          </p>
        </div>
      </section>
     
      <div class="container">
        {% for img in img_list %}
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <img src="{{ img.file.url }}" alt="{{ img.title }}" width="70" height="70">
            </div>
            <div class="col-xs-12 col-sm-6">
              <p>{{ img.title }}</p>
              <a href="{% url 'app:update' img.pk %}" class="btn btn-outline-primary">
                更新する
              </a>
              <a href="{% url 'app:delete' img.pk %}" class="btn btn-outline-primary">
                削除する
              </a>
            </div>
          </div>
        {% endfor %}
     
        <div class="text-xs-center">
          {% include "app/page.html" %}
        </div>
     
      </div>
<a href="{% url 'admin:index' %}">管理画面へ</a>


<hr>

examples/django/応用/画像アプロダ（CRUD処理を、汎用ビューで）/project/app/templates/app/page.html
<nav aria-label="Page navigation">
        <ul class="pagination">
       
            {% if page_obj.has_previous %}
              <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% endif %}
          
            {% for link_page in page_obj.paginator.page_range %}
              {% if link_page == page_obj.number %}
                <li class="page-item active">
                  <a class="page-link" href="?page={{ link_page }}">
                    {{ link_page }}
                  </a>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ link_page }}">
                    {{ link_page }}
                  </a>
                </li>
              {% endif %}
            {% endfor %}
          
            {% if page_obj.has_next %}
              <li class="page-item">
              <a class="page-link" href="?page={{  page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            {% endif %}
          
        </ul>
      </nav>